[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dtrm.uk"
authors = [{name = "Daleterrence", email = "null"}]
dynamic = ["version", "description"]
